name: caffeinated
description: "Keeps the Android screen on for a set duration or indefinitely, even after you leave the app."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
  permission_handler: ^11.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  fonts:
    - family: Archivo Black
      fonts:
        - asset: assets/fonts/ArchivoBlack-Regular.ttf
    - family: Major Mono Display
      fonts:
        - asset: assets/fonts/MajorMonoDisplay-Regular.ttf
    - family: DM Serif Display Italic
      fonts:
        - asset: assets/fonts/DMSerifDisplay-Italic.ttf
          style: italic
    - family: Space Grotesk
      fonts:
        - asset: assets/fonts/SpaceGrotesk-Variable.ttf
